# Just testing eProsima-CI
name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  ubuntu-test-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Build documentation, test and upload
        uses: jparisu/eProsima-CI/actions/sphinx_docs@feature/docs
        with:
          docs_subpackage_name: amlip_docs
