name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:

  ubuntu-test-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Sync eProsima/AML-IP repository
        uses: jparisu/eProsima-CI/ubuntu/install_colcon@feature/docs
        with:
          docs_subpackage_name: amlip_docs
